service: h4ktube-proxy

provider:
  name: google
  runtime: nodejs
  project: h4k-tube
  credentials: service_key.json
  memorySize: 512
  timeout: 540s
  labels:
    application: H4kTube Proxy

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn*
    - service_key.json
  include:
    - ../dist/**
    - ../sitemap.xml
    - "*.js"

functions:
  proxy:
    handler: proxy
    events:
      - http: path
